Umgebungsvariablen, Distributionsfamilien, Packetverwaltung
LorenzHohermuth/bbw-linux-cookbook pull request #10
Opened 2023-06-16 06:25 UTC by jannismilz

Meine Einträge:
- `Umgebungsvariablen`
- `Distributionsfamilien`
- `Packetverwaltung` (Titelseite)

2023-06-16 06:58 UTC, LorenzHohermuth requested changes
füge noch ein paar Bilder hinzu aber sonst sehr gut 👍

2023-06-16 06:58 UTC, LorenzHohermuth commented on paketverwaltung/distributionsfamilien.md
> +Distributionsfamilien in Linux bieten eine Möglichkeit, die Beziehungen zwischen verschiedenen Distributionen zu kategorisieren und zu verstehen. Sie spiegeln das gemeinsame Erbe, die Codebasis und d
Füge doch noch ein paar Grafiken ein, damit man sich auch besser was vorstellen kann

2023-06-23 06:38 UTC, jannismilz commented on paketverwaltung/distributionsfamilien.md
> +Distributionsfamilien in Linux bieten eine Möglichkeit, die Beziehungen zwischen verschiedenen Distributionen zu kategorisieren und zu verstehen. Sie spiegeln das gemeinsame Erbe, die Codebasis und d
Gemacht

2023-06-30 06:09 UTC, LorenzHohermuth approved these changes

2023-06-30 06:11 UTC, merged