Artikel geschrieben
LorenzHohermuth/bbw-linux-cookbook pull request #14
Opened 2023-06-23 09:14 UTC by standbee

Pipes und Umleitung
bash Scripting

2023-06-30 05:51 UTC, LorenzHohermuth commented on bash-console/pipes-und-umleitung.md
> +## Activitäten
alle im einheitlichem deutsch

2023-06-30 05:57 UTC, LorenzHohermuth commented on bash-console/pipes-und-umleitung.md
> +    user@bash:
Code Blocks mit ` um runden und als bash definieren für Syntax highlighting

2023-06-30 06:00 UTC, LorenzHohermuth requested changes
Code mit ` umrunden und als bash markieren
+ ein Titel ist nicht einheitliches deutsch

2023-06-30 06:50 UTC, standbee commented
> Code mit ` umrunden und als bash markieren
> 
>     * ein Titel ist nicht einheitliches deutsch

Welcher Titel ist nicht einheitliches Deutsch?

2023-06-30 15:30 UTC, LorenzHohermuth commented
Auf Linie 228 im File Pipelines

2023-07-11 06:56 UTC, jannismilz approved these changes

2023-07-11 07:42 UTC, LorenzHohermuth approved these changes
Wir müssen jz einfach Mergen auch wenn alles noch nicht gut ist

2023-07-11 07:42 UTC, merged