Contribution with 2 Files :D
LorenzHohermuth/bbw-linux-cookbook pull request #16
Opened 2023-06-30 08:17 UTC by Sniper0141

# New contents

- IP-Adressen zuweisen
- Netzverbindung aufbauen

2023-06-30 15:48 UTC, LorenzHohermuth requested changes

2023-06-30 15:48 UTC, LorenzHohermuth commented on netzwerkkonfiguration/IP-Adresse_zuweisen.md
vlt auf den `ifconfig` befehl genauer eingehen und ein paar flags sage wie die `-a` und co.

2023-06-30 15:48 UTC, LorenzHohermuth commented on netzwerkkonfiguration/Netzverbindung_aufbauen.md
> +``sudo nmcli dev wifi connect [deine SSID]``
Die eckigen Klammern weg und anstellen von `deine SSID` -> `YOUR_SSID`

2023-06-30 15:48 UTC, LorenzHohermuth commented on netzwerkkonfiguration/Netzverbindung_aufbauen.md
> +``sudo nmcli dev wifi connect network-ssid password "[dein Passwort]"``
Die eckigen Klammern weg und anstellen von `dein Passwort` -> `YOUR_PASSWORD`

2023-07-07 05:43 UTC, Sniper0141 commented on netzwerkkonfiguration/Netzverbindung_aufbauen.md
> +``sudo nmcli dev wifi connect [deine SSID]``
Gemacht

2023-07-07 05:44 UTC, Sniper0141 commented on netzwerkkonfiguration/Netzverbindung_aufbauen.md
> +``sudo nmcli dev wifi connect network-ssid password "[dein Passwort]"``
Gemacht

2023-07-07 05:48 UTC, LorenzHohermuth requested changes
👍

2023-07-07 06:18 UTC, LorenzHohermuth approved these changes
👍

2023-07-07 06:18 UTC, Sniper0141 commented on netzwerkkonfiguration/IP-Adresse_zuweisen.md
Auch gemacht

2023-07-07 06:18 UTC, merged