added DNS-Konfiguration.md and changes Firewall-Konfiguration.md
LorenzHohermuth/bbw-linux-cookbook pull request #28
Opened 2023-07-06 09:25 UTC by Valona1

2023-07-06 09:32 UTC, jannismilz requested changes

2023-07-06 09:32 UTC, jannismilz commented on DNS-Konfiguration.md
> +<span style="color: white">.</span>
Für was ist dieser Punkt genau? 😅

2023-07-06 09:32 UTC, jannismilz commented on Firewall-Konfiguration.md
> +<span style="color: white">.</span>
Gleiche Frage wie oben

2023-07-06 09:33 UTC, jannismilz requested changes
Bitte füge deine Einträge noch ins `SUMMARY.md` wie im Leitfadne beschrieben.

2023-07-06 09:36 UTC, Valona1 commented on DNS-Konfiguration.md
> +<span style="color: white">.</span>
Den Punkt habe ich gemacht weil bei mir es angezeigt hat das es keinen Abstand hatte zum Titel du kannst es aber auch weglassen.

2023-07-06 09:39 UTC, jannismilz commented on DNS-Konfiguration.md
> +<span style="color: white">.</span>
Doch es wird schon einen Abstand haben. Nimm doch beide Punkte raus.

2023-07-07 06:01 UTC, jannismilz approved these changes

2023-07-07 06:01 UTC, merged