Ordner und Deckblatt linux aufbau. eintrag Summary
LorenzHohermuth/bbw-linux-cookbook pull request #7
Opened 2023-06-02 06:42 UTC by bambinaCh

Neuer Ordner und Deckblat für "Aufbau von Linux". Diese auch in Summary hinzufügt

2023-06-02 07:00 UTC, bambinaCh reviewed
Neuer Ordner und Deckblat für "Aufbau von Linux". Diese auch in Summary hinzufügt

2023-06-02 07:04 UTC, jannismilz requested changes

2023-06-02 07:04 UTC, jannismilz commented on SUMMARY.md
> +* [Aufbau von Linux](/Aufbau-von-Linux/)
- (optional) Nutze Emojis für die 1. Überschrift.
- Achte dich auf `camel-case` (alles klein geschrieben und durch - getrennt)
- Du verlinkst zu einem Verzeichnis, das wird nicht funktionieren. (Ändere link zu: `aufbau-von-linux/aufbau-von-linux.md`)

2023-06-02 07:04 UTC, jannismilz commented on Aufbau-von-Linux/Aufbau-von-Linux.md
> +# H1 Aufbau von Linux
- Entferne dieses `H1`

2023-06-02 07:04 UTC, jannismilz commented on Aufbau-von-Linux/Aufbau-von-Linux.md
> +Linux-Systeme bestehen aus drei Komponenten: **Bootloader**, **Linux-Kernel** und **Root-Filesystem**. Der Bootloader hat die Aufgabe beim Booten die Hardware zu initialisieren, den Kernel ins RAM zu
Schreibe doch noch etwas mehr über den Aufbau von Linux, die Geschichte, z.B. kurz wer Linus Torvalds, Maskottchen etc.

2023-07-06 07:14 UTC, jannismilz commented on SUMMARY.md
> +* [Aufbau von Linux](/Aufbau-von-Linux/)
@bambinaCh bitte das auch noch machen.

Um case-sensitive changes zu commiten musst du das auführen: `git config core.ignorecase false`

2023-07-06 08:59 UTC, jannismilz approved these changes

2023-07-06 08:59 UTC, merged